variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'From-AzurePortal'
    appType: 'webAppLinux'
    appName: 'webfrom-rd'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'